const scenes=[...document.querySelectorAll('.scene')], progress=document.getElementById('progress');
let step=0,audioOn=false,audioCtx,master;
function vibrate(p=12){if(navigator.vibrate)navigator.vibrate(p)}
function ensureAudio(){if(audioCtx)return;audioCtx=new(window.AudioContext||window.webkitAudioContext)();master=audioCtx.createGain();master.gain.value=.13;master.connect(audioCtx.destination);audioOn=true;document.getElementById('sound').classList.add('on');document.getElementById('sound').textContent='♪';ambient()}
function tone(freq=440,dur=.12,type='sine',vol=.18){if(!audioOn)return;const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(vol,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+dur);o.connect(g);g.connect(master);o.start();o.stop(audioCtx.currentTime+dur)}
function ambient(){if(!audioOn)return;const o=audioCtx.createOscillator(),g=audioCtx.createGain(),f=audioCtx.createBiquadFilter();o.type='sine';o.frequency.value=54;g.gain.value=.035;f.type='lowpass';f.frequency.value=170;o.connect(f);f.connect(g);g.connect(master);o.start()}
document.getElementById('sound').onclick=()=>{if(!audioCtx){ensureAudio();tone(520,.18)}else{audioOn=!audioOn;master.gain.value=audioOn?.13:0;document.getElementById('sound').classList.toggle('on',audioOn);document.getElementById('sound').textContent=audioOn?'♪':'◌'}};
function go(n){ensureAudio();tone(350+n*28,.16);vibrate(10);scenes[step].classList.add('exit');setTimeout(()=>{scenes[step].classList.remove('active','exit');step=n;scenes[step].classList.add('active');progress.style.width=(step/(scenes.length-1)*100)+'%';onEnter(step)},240)}
function onEnter(n){if(n===5)buildWheel();if(n===7)runTerminal();if(n===8){burst(innerWidth/2,innerHeight*.72,36);tone(440,.6);setTimeout(()=>tone(660,.8),170)}}
function toast(t){const el=document.getElementById('toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1500)}
function burst(x,y,count=18){for(let i=0;i<count;i++){const s=document.createElement('i');s.className='spark';s.style.left=x+'px';s.style.top=y+'px';const a=Math.random()*Math.PI*2,d=45+Math.random()*130;s.style.setProperty('--x',Math.cos(a)*d+'px');s.style.setProperty('--y',Math.sin(a)*d+'px');document.body.appendChild(s);setTimeout(()=>s.remove(),1200)}}
const finger=document.getElementById('finger'),fill=finger.querySelector('.fill'),fNext=document.getElementById('fingerNext'),fText=document.getElementById('fingerText');let holdStart,holdAnim;
function holdBegin(e){e.preventDefault();ensureAudio();holdStart=performance.now();clearInterval(holdAnim);holdAnim=setInterval(()=>{const p=Math.min(1,(performance.now()-holdStart)/2000);fill.style.height=(p*100)+'%';fText.textContent='совпадение '+Math.round(p*100)+'%';if(p>=1){clearInterval(holdAnim);finger.classList.add('done');fText.textContent='личность подтверждена';fNext.disabled=false;tone(680,.35);vibrate([18,40,28]);burst(innerWidth/2,finger.getBoundingClientRect().top+82,20)}},45)}
function holdEnd(){if(fNext.disabled){clearInterval(holdAnim);fill.style.height='0';fText.textContent='удерживай, не отпускай'}}
finger.addEventListener('pointerdown',holdBegin);['pointerup','pointercancel','pointerleave'].forEach(ev=>finger.addEventListener(ev,holdEnd));
const seat=document.getElementById('rightSeat'),carNext=document.getElementById('carNext'),carClue=document.getElementById('carClue');
function revealSeat(){seat.classList.add('revealed');carClue.classList.add('show');carNext.disabled=false;tone(560,.25);vibrate(18);toast('точка начала найдена')}
seat.onclick=revealSeat;document.getElementById('seatHint').onclick=()=>{seat.animate([{transform:'translateY(0)'},{transform:'translateY(-8px)'},{transform:'translateY(0)'}],{duration:550});tone(310,.12)};
let routeExpected=1;document.querySelectorAll('.choice').forEach(c=>c.onclick=()=>{ensureAudio();const v=+c.dataset.choice;if(v===routeExpected){c.classList.add('selected');routeExpected++;tone(420+v*90,.2);vibrate(10);const texts=['','автомагазин →','автомагазин → Теремок →','автомагазин → Теремок → ночные разговоры'];document.getElementById('sequence').textContent=texts[routeExpected-1];if(routeExpected===4){document.getElementById('routeNext').disabled=false;toast('нелепо, но всё совпало')}}else{tone(150,.18,'sawtooth',.1);vibrate([20,40,20]);c.animate([{transform:'translateX(0)'},{transform:'translateX(-8px)'},{transform:'translateX(8px)'},{transform:'translateX(0)'}],{duration:300})}});
const slider=document.getElementById('timeSlider'),clock=document.getElementById('clock'),driveCopy=document.getElementById('driveCopy'),driveNext=document.getElementById('driveNext');slider.oninput=()=>{const p=+slider.value,total=1360+Math.round(p*3.8),h=Math.floor(total/60)%24,m=total%60;clock.textContent=String(h).padStart(2,'0')+':'+String(m).padStart(2,'0');if(p>70)driveCopy.classList.add('show');if(p>=96){driveNext.disabled=false;clock.textContent='05:00';toast('снова до утра');vibrate(14)}};
let wheelBuilt=false,lit=0;function buildWheel(){if(wheelBuilt)return;wheelBuilt=true;const w=document.getElementById('wheel');for(let i=0;i<12;i++){const s=document.createElement('i');s.className='spoke';s.style.transform=`translate(-50%,-50%) rotate(${i*15}deg)`;w.appendChild(s)}for(let i=0;i<10;i++){const c=document.createElement('button');c.className='cabin';const a=i/10*Math.PI*2,r=50;c.style.left=(50+Math.cos(a)*r)+'%';c.style.top=(50+Math.sin(a)*r)+'%';c.onclick=e=>{e.stopPropagation();if(c.classList.contains('on'))return;c.classList.add('on');lit++;document.getElementById('lightsCount').textContent=lit;tone(460+lit*55,.22);vibrate(8);if(lit===5){document.getElementById('parkNext').disabled=false;document.getElementById('parkMsg').innerHTML='Место было просто декорацией. <b style="color:var(--gold2)">Запомнился человек рядом.</b>';burst(innerWidth/2,innerHeight*.5,28)}};w.appendChild(c)}}
const box=document.getElementById('distanceBox'),livePath=document.getElementById('livePath'),packet=document.getElementById('packet'),distNext=document.getElementById('distanceNext');let distTimer;
function distStart(e){e.preventDefault();ensureAudio();livePath.classList.add('draw');packet.classList.add('go');tone(260,.5);distTimer=setTimeout(()=>{distNext.disabled=false;document.getElementById('distanceCopy').innerHTML='Расстояние есть на карте. <b style="color:var(--gold2)">Но оно ничего не отменило.</b>';tone(620,.4);vibrate([15,35,25]);toast('связь восстановлена')},1900)}
function distEnd(){if(distNext.disabled){clearTimeout(distTimer);livePath.classList.remove('draw');packet.classList.remove('go');void packet.offsetWidth}}
box.addEventListener('pointerdown',distStart);['pointerup','pointercancel','pointerleave'].forEach(e=>box.addEventListener(e,distEnd));
function runTerminal(){const lines=['> восстановление событий...','> случайная встреча: <b>подтверждено</b>','> автомагазин + Теремок: <b>почему-то важно</b>','> ночные разговоры: <b>слишком много</b>','> расстояние: <b>временная помеха</b>','> причина сохранения: <b>не системная</b>'];const t=document.getElementById('terminal'),box=document.getElementById('systemBox');t.innerHTML='';document.getElementById('systemNext').disabled=true;lines.forEach((l,i)=>setTimeout(()=>{t.innerHTML+=l+'<br>';tone(280+i*35,.08,'square',.04);if(i===lines.length-1){box.classList.add('glitch');document.getElementById('systemNext').disabled=false;vibrate([12,30,12])}},i*520))}
function restart(){location.reload()}
progress.style.width='0%';