const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const chapters=$$('.chapter'), canvas=$('#scene'), ctx=canvas.getContext('2d');
let chapter=0, W=0,H=0,dpr=1,last=0, audioOn=false,audioCtx,master, rainDrops=[], roadOffset=0, speed=.25, dawn=0, wheelAngle=0, routeProgress=0, wipeProgress=0;
let sceneMode='black', seatGlow=0, connected=false;
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
function resize(){dpr=Math.min(2,devicePixelRatio||1);W=innerWidth;H=innerHeight;canvas.width=W*dpr;canvas.height=H*dpr;canvas.style.width=W+'px';canvas.style.height=H+'px';ctx.setTransform(dpr,0,0,dpr,0,0);makeRain()}
addEventListener('resize',resize);resize();
function makeRain(){rainDrops=Array.from({length:Math.round(W/5)},()=>({x:Math.random()*W,y:Math.random()*H,l:12+Math.random()*38,s:.25+Math.random()*.7}))}
function vibrate(p=12){navigator.vibrate?.(p)}
function ensureAudio(){if(audioCtx)return;audioCtx=new(window.AudioContext||window.webkitAudioContext)();master=audioCtx.createGain();master.gain.value=.16;master.connect(audioCtx.destination);audioOn=true;$('#sound').classList.add('on');ambient()}
function tone(f=420,d=.12,type='sine',v=.14){if(!audioOn)return;const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.setValueAtTime(f,audioCtx.currentTime);g.gain.setValueAtTime(v,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+d);o.connect(g);g.connect(master);o.start();o.stop(audioCtx.currentTime+d)}
function ambient(){if(!audioOn)return;const o=audioCtx.createOscillator(),g=audioCtx.createGain(),f=audioCtx.createBiquadFilter();o.type='sawtooth';o.frequency.value=42;f.type='lowpass';f.frequency.value=120;g.gain.value=.018;o.connect(f);f.connect(g);g.connect(master);o.start()}
$('#sound').addEventListener('click',()=>{ensureAudio();tone(520,.08);vibrate(8)});
let transitioning=false;
function setChapter(n,immediate=false){
  const apply=()=>{chapter=n;chapters.forEach((c,i)=>c.classList.toggle('active',i===n));$('#progress').style.width=(n/8*100)+'%';$('#hud').classList.toggle('show',n>0&&n<8);sceneMode=['black','car','route','rain','night','park','distance','shutdown','final'][n];tone(260+n*38,.15,'sine',.1);vibrate(10);if(n===1)seatGlow=1;if(n===4){speed=.35;dawn=0}if(n===7)setTimeout(runShutdown,500)};
  if(immediate){apply();return} if(transitioning)return;transitioning=true;const cut=$('#cinematicCut');cut.classList.add('on');setTimeout(()=>{apply();setTimeout(()=>{cut.classList.remove('on');transitioning=false},80)},340)
}
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1400)}
function hold(el,ms,progress,onDone){let t=0,raf,start=0,active=false;const stop=()=>{active=false;cancelAnimationFrame(raf);if(t<1){t=0;progress(0)}};const tick=now=>{if(!active)return;if(!start)start=now;t=clamp((now-start)/ms);progress(t);if(t>=1){active=false;onDone()}else raf=requestAnimationFrame(tick)};const begin=e=>{e.preventDefault();ensureAudio();active=true;start=0;raf=requestAnimationFrame(tick)};el.addEventListener('pointerdown',begin);addEventListener('pointerup',stop);addEventListener('pointercancel',stop)}
hold($('#unlockHold'),1900,t=>{$('#unlockHold .ring').style.strokeDashoffset=339.3*(1-t);if(t>.2)tone(170+t*180,.035,'sine',.018)},()=>{tone(620,.25,'sine',.2);setTimeout(()=>setChapter(1),350)});
$('#seatHotspot').addEventListener('click',()=>{ensureAudio();seatGlow=2;tone(360,.16);$('#seatHint').textContent='Совпадение найдено';$('#seatHotspot small').textContent='именно здесь';setTimeout(()=>setChapter(2),1450)});
const routeLine=$('.route-line'),thumb=$('#routeThumb'),fill=$('#routeFill');let dragging=false;
function routeAt(x){const r=routeLine.getBoundingClientRect();routeProgress=clamp((x-r.left)/r.width);thumb.style.left=(routeProgress*100)+'%';fill.style.width=(routeProgress*100)+'%';$('#routePercent').textContent=Math.round(routeProgress*100)+'%';$$('.route-labels div').forEach((d,i)=>d.classList.toggle('on',routeProgress>=[.05,.48,.87][i]));$('#navCaption').textContent=routeProgress<.33?'Первая точка — автомагазин':routeProgress<.7?'Потом Теремок':routeProgress<.98?'А дальше — просто ехать куда угодно':'Маршрут восстановлен. Абсурдно, но точно.';speed=.35+routeProgress*.7;if(routeProgress>.985&&!connected){connected=true;tone(720,.22);vibrate([16,35,16]);setTimeout(()=>{connected=false;setChapter(3)},1350)}}
thumb.addEventListener('pointerdown',e=>{dragging=true;thumb.setPointerCapture(e.pointerId);ensureAudio()});thumb.addEventListener('pointermove',e=>{if(dragging)routeAt(e.clientX)});thumb.addEventListener('pointerup',()=>dragging=false);routeLine.addEventListener('pointerdown',e=>{ensureAudio();routeAt(e.clientX)});
const wipe=$('#wipeLayer');let wiping=false,lastPoint=null;
function wipeAt(x,y){wipeProgress=clamp(wipeProgress+.018);wipe.style.setProperty('--x',x+'px');wipe.style.setProperty('--y',y+'px');wipe.style.setProperty('--r',(45+wipeProgress*Math.min(W,H)*.62)+'px');if(wipeProgress>.25)$('#wipeMessage').classList.add('show');if(wipeProgress>.92&&!connected){connected=true;$('#wipeHint').textContent='Шум убран';tone(660,.25);setTimeout(()=>{connected=false;setChapter(4)},1800)}}
wipe.addEventListener('pointerdown',e=>{wiping=true;ensureAudio();wipe.setPointerCapture(e.pointerId);wipeAt(e.clientX,e.clientY)});wipe.addEventListener('pointermove',e=>{if(wiping){wipeAt(e.clientX,e.clientY);if(lastPoint&&Math.hypot(e.clientX-lastPoint.x,e.clientY-lastPoint.y)>12)tone(190+wipeProgress*80,.025,'sine',.01);lastPoint={x:e.clientX,y:e.clientY}}});wipe.addEventListener('pointerup',()=>wiping=false);
let accelerating=false,accStart=0,accRaf;
const accel=$('#accelerator');
function accelTick(t){if(!accelerating)return;if(!accStart)accStart=t;const p=clamp((t-accStart)/4200);speed=.8+p*3.2;dawn=p;const minutes=Math.round(22*60+41+p*(6*60+52));const h=Math.floor((minutes%(24*60))/60),m=minutes%60;$('#clock').textContent=String(h).padStart(2,'0')+':'+String(m).padStart(2,'0');$('#clockDate').textContent=p>.2?'УЖЕ ЗАВТРА':'СЕГОДНЯ';$('#nightLine').textContent=p<.35?'Мои тупые истории. Твои реакции. И город за окном.':p<.72?'Время было где-то рядом, но мы его особо не замечали.':'И каждый раз появлялся один и тот же вопрос: почему уже светло?';if(p>=1){accelerating=false;accel.classList.remove('pressed');tone(760,.28);setTimeout(()=>setChapter(5),1200);return}accRaf=requestAnimationFrame(accelTick)}
function accelStartFn(e){e.preventDefault();ensureAudio();accelerating=true;accStart=0;accel.classList.add('pressed');accRaf=requestAnimationFrame(accelTick)}
function accelStop(){accelerating=false;accel.classList.remove('pressed');cancelAnimationFrame(accRaf);speed=.5}
accel.addEventListener('pointerdown',accelStartFn);addEventListener('pointerup',accelStop);addEventListener('pointercancel',accelStop);
const wheel=$('#wheelUI'),ring=$('#wheelRing');let wheelDrag=false,prevAngle=0,totalSpin=0,lights=0;
function ang(e){const r=wheel.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2;return Math.atan2(e.clientY-cy,e.clientX-cx)}
wheel.addEventListener('pointerdown',e=>{ensureAudio();wheelDrag=true;prevAngle=ang(e);wheel.setPointerCapture(e.pointerId)});wheel.addEventListener('pointermove',e=>{if(!wheelDrag)return;let a=ang(e),d=a-prevAngle;if(d>Math.PI)d-=Math.PI*2;if(d<-Math.PI)d+=Math.PI*2;wheelAngle+=d;totalSpin+=Math.abs(d);prevAngle=a;ring.style.transform=`rotate(${wheelAngle}rad)`;const next=Math.min(12,Math.floor(totalSpin/(Math.PI*2)*4)+1);if(next>lights){lights=next;$$('.wheel-ring i').slice(0,lights).forEach(i=>i.classList.add('on'));tone(310+lights*25,.08,'sine',.07)}if(lights>=12&&!connected){connected=true;$('#parkCopy').classList.add('show');vibrate([10,30,10]);setTimeout(()=>{connected=false;setChapter(6)},2200)}});wheel.addEventListener('pointerup',()=>wheelDrag=false);
const map=$('#distanceMap'),cities=$$('.city');let activeCities=new Set();
function touchCities(touches){activeCities.clear();for(const t of touches){for(const c of cities){const r=c.getBoundingClientRect();if(t.clientX>=r.left&&t.clientX<=r.right&&t.clientY>=r.top&&t.clientY<=r.bottom)activeCities.add(c.dataset.city)}}cities.forEach(c=>c.classList.toggle('touch',activeCities.has(c.dataset.city)));if(activeCities.size===2)connectCities()}
map.addEventListener('touchstart',e=>{ensureAudio();touchCities(e.touches)},{passive:true});map.addEventListener('touchmove',e=>touchCities(e.touches),{passive:true});map.addEventListener('touchend',e=>touchCities(e.touches),{passive:true});
function connectCities(){if(connected)return;connected=true;$('#livePath').style.strokeDashoffset=0;$('#signal').classList.add('run');$('.distance-copy').classList.add('show');tone(220,.6,'sine',.12);setTimeout(()=>tone(440,.5,'sine',.1),450);vibrate([18,50,18]);setTimeout(()=>setChapter(7),2600)}
$('#oneFinger').addEventListener('click',()=>{ensureAudio();toast('Проведи от точки «ТЫ» к точке «Я»');let drawing=false;const start=e=>{drawing=true;map.setPointerCapture(e.pointerId)};const move=e=>{if(!drawing)return;const b=cities[1].getBoundingClientRect();if(e.clientX>b.left&&e.clientX<b.right&&e.clientY>b.top&&e.clientY<b.bottom)connectCities()};map.addEventListener('pointerdown',start,{once:true});map.addEventListener('pointermove',move)});
function runShutdown(){speed=.08;setTimeout(()=>tone(88,1.1,'sine',.08),300)}
$('#truthButton').addEventListener('click',()=>{$('#shutdownCopy').classList.add('fade');tone(520,.35,'sine',.15);setTimeout(()=>setChapter(8),800)});
$('#replay').addEventListener('click',()=>location.reload());
function lerp(a,b,t){return a+(b-a)*t}
function rounded(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}
function drawBlack(){ctx.fillStyle='#020202';ctx.fillRect(0,0,W,H);const g=ctx.createRadialGradient(W*.5,H*.38,0,W*.5,H*.38,Math.min(W,H)*.58);g.addColorStop(0,'rgba(105,72,39,.12)');g.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=g;ctx.fillRect(0,0,W,H)}
function drawRoad(ts,night=true){roadOffset+=(ts-last)*speed*.09;const horizon=H*.46;const sky=ctx.createLinearGradient(0,0,0,horizon);const d=clamp(dawn);sky.addColorStop(0,`rgb(${lerp(4,75,d)},${lerp(7,74,d)},${lerp(10,92,d)})`);sky.addColorStop(1,`rgb(${lerp(16,194,d)},${lerp(18,133,d)},${lerp(22,85,d)})`);ctx.fillStyle=sky;ctx.fillRect(0,0,W,horizon+10);for(let i=0;i<34;i++){const x=(i*97+37)%W,y=horizon-45-(i*53)%Math.max(80,horizon-70);ctx.fillStyle=`rgba(255,${160+(i%3)*20},95,${.12+(i%4)*.04})`;ctx.beginPath();ctx.arc(x,y,1.4+(i%3),0,Math.PI*2);ctx.fill()}
ctx.fillStyle='#090a0a';ctx.fillRect(0,horizon,W,H-horizon);ctx.beginPath();ctx.moveTo(W*.42,horizon);ctx.lineTo(W*.58,horizon);ctx.lineTo(W*.94,H);ctx.lineTo(W*.06,H);ctx.closePath();ctx.fillStyle='#0e0f0f';ctx.fill();ctx.strokeStyle='rgba(255,255,255,.1)';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(W*.42,horizon);ctx.lineTo(W*.06,H);ctx.moveTo(W*.58,horizon);ctx.lineTo(W*.94,H);ctx.stroke();for(let i=0;i<9;i++){const p=((i/9+roadOffset*.002)%1);const y=lerp(horizon,H,p*p),w=lerp(1,14,p),x=W/2;ctx.fillStyle='rgba(225,210,180,.32)';ctx.fillRect(x-w/2,y,w,lerp(8,58,p))}
for(let side of [-1,1])for(let i=0;i<9;i++){const p=((i/9+roadOffset*.0016)%1),y=lerp(horizon,H,p*p),x=W/2+side*lerp(W*.1,W*.52,p),r=lerp(1.5,9,p);ctx.fillStyle=`rgba(255,196,110,${.12+p*.5})`;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill()}}
function drawCarInterior(){ctx.save();ctx.fillStyle='rgba(0,0,0,.96)';ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(W,0);ctx.lineTo(W*.91,H*.18);ctx.lineTo(W*.83,H*.48);ctx.lineTo(W*.17,H*.48);ctx.lineTo(W*.09,H*.18);ctx.closePath();ctx.fill();ctx.strokeStyle='rgba(255,255,255,.07)';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(W*.17,H*.48);ctx.lineTo(W*.09,H*.18);ctx.lineTo(W*.91,H*.18);ctx.lineTo(W*.83,H*.48);ctx.stroke();ctx.fillStyle='#060606';ctx.beginPath();ctx.moveTo(0,H*.74);ctx.quadraticCurveTo(W*.5,H*.58,W,H*.74);ctx.lineTo(W,H);ctx.lineTo(0,H);ctx.closePath();ctx.fill();const g=ctx.createLinearGradient(0,H*.63,0,H);g.addColorStop(0,'rgba(28,25,20,.8)');g.addColorStop(1,'#030303');ctx.fillStyle=g;ctx.fill();ctx.fillStyle='#0e0e0d';rounded(W*.29,H*.69,W*.42,H*.12,18);ctx.fill();ctx.strokeStyle='rgba(255,255,255,.08)';ctx.stroke();ctx.fillStyle='rgba(212,173,115,.08)';rounded(W*.34,H*.715,W*.32,H*.065,10);ctx.fill();ctx.restore()}
function drawSeat(){const x=W*.68,y=H*.57,w=W*.26,h=H*.34;ctx.save();const glow=seatGlow===2?.5:.12;ctx.shadowColor=`rgba(212,173,115,${glow})`;ctx.shadowBlur=seatGlow===2?44:12;ctx.fillStyle='#111110';rounded(x,y,w,h,Math.min(45,w*.25));ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle='rgba(255,255,255,.08)';ctx.stroke();ctx.fillStyle='#090909';rounded(x+w*.16,y-h*.12,w*.68,h*.2,28);ctx.fill();ctx.restore()}
function drawRain(ts){for(const r of rainDrops){r.y+=r.s*(ts-last)*.15;if(r.y>H+40){r.y=-40;r.x=Math.random()*W}ctx.strokeStyle=`rgba(195,211,216,${.05+r.s*.09})`;ctx.lineWidth=.7;ctx.beginPath();ctx.moveTo(r.x,r.y);ctx.lineTo(r.x-2,r.y+r.l);ctx.stroke()}}
function drawPark(ts){drawRoad(ts);const cx=W*.68,cy=H*.48,R=Math.min(W,H)*.25;ctx.save();ctx.strokeStyle='rgba(242,214,165,.2)';ctx.lineWidth=1;ctx.beginPath();ctx.arc(cx,cy,R,0,Math.PI*2);ctx.stroke();for(let i=0;i<16;i++){const a=i/16*Math.PI*2+roadOffset*.0002;ctx.beginPath();ctx.moveTo(cx,cy);ctx.lineTo(cx+Math.cos(a)*R,cy+Math.sin(a)*R);ctx.stroke();ctx.fillStyle=`rgba(242,214,165,${.18+(i%3)*.06})`;ctx.beginPath();ctx.arc(cx+Math.cos(a)*R,cy+Math.sin(a)*R,2.5,0,Math.PI*2);ctx.fill()}ctx.restore()}
function drawDistance(){drawBlack();const g=ctx.createRadialGradient(W*.18,H*.3,0,W*.18,H*.3,W*.42);g.addColorStop(0,'rgba(61,77,99,.13)');g.addColorStop(1,'transparent');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);const g2=ctx.createRadialGradient(W*.82,H*.72,0,W*.82,H*.72,W*.4);g2.addColorStop(0,'rgba(118,74,38,.14)');g2.addColorStop(1,'transparent');ctx.fillStyle=g2;ctx.fillRect(0,0,W,H)}
function render(ts){ctx.clearRect(0,0,W,H);if(sceneMode==='black'||sceneMode==='shutdown'||sceneMode==='final')drawBlack();else if(sceneMode==='distance')drawDistance();else{if(sceneMode==='park')drawPark(ts);else drawRoad(ts);drawCarInterior();if(sceneMode==='car')drawSeat();if(sceneMode==='rain')drawRain(ts);if(sceneMode==='night'&&dawn>.62){ctx.fillStyle=`rgba(255,186,112,${(dawn-.62)*.12})`;ctx.fillRect(0,0,W,H)}}last=ts;requestAnimationFrame(render)}requestAnimationFrame(render);
setChapter(0,true);
