(()=>{
'use strict';
const $=(s,c=document)=>c.querySelector(s),$$=(s,c=document)=>[...c.querySelectorAll(s)];
const TELEGRAM='https://t.me/zhukov_boss';
const fullRub=n=>new Intl.NumberFormat('ru-RU').format(Math.round(n/1000)*1000)+' ₽';
const compact=n=>{n=Math.max(0,n);if(n>=1e6)return(n/1e6).toLocaleString('ru-RU',{minimumFractionDigits:2,maximumFractionDigits:2})+' млн ₽';if(n>=1e5)return Math.round(n/1000).toLocaleString('ru-RU')+' тыс. ₽';return fullRub(n)};
const compactRange=(a,b)=>Math.abs(b-a)<5000?compact((a+b)/2):`${compact(a)} — ${compact(b)}`;

// All contact buttons are native, same-tab links to the one verified username.
$$('a[href*="t.me/"]').forEach(a=>{a.href=TELEGRAM;a.removeAttribute('target');a.removeAttribute('rel');});

const progress=$('#pageProgress'),mobileCta=$('#mobileCta'),toast=$('#leadToast');
let scrollRaf=0,toastTimer=0;
function showToast(text){if(!toast)return;clearTimeout(toastTimer);toast.textContent=text;toast.classList.add('show');toastTimer=setTimeout(()=>toast.classList.remove('show'),2600);}
function animateMoney(el,to,duration=420){if(!el)return;cancelAnimationFrame(el._raf);const from=Number(el.dataset.current||String(el.textContent).replace(/\D/g,'')||0),started=performance.now();const tick=now=>{const t=Math.min(1,(now-started)/duration),value=Math.round(from+(to-from)*(1-Math.pow(1-t,3)));el.textContent=fullRub(value);el.dataset.current=String(value);if(t<1)el._raf=requestAnimationFrame(tick);else{el.textContent=fullRub(to);el.dataset.current=String(to);}};el._raf=requestAnimationFrame(tick);}

// Matched before / after comparison.
const demo=$('#beforeAfter'),after=$('#afterLayer'),splitLine=$('#splitLine'),splitHandle=$('#splitHandle');
let split=52,dragging=false,userTouched=false,startX=0,startY=0,horizontal=false;
function setSplit(value,instant=false){if(!demo)return;split=Math.max(0,Math.min(100,value));demo.style.setProperty('--split',split+'%');if(after)after.style.clipPath=`inset(0 0 0 ${split}%)`;if(splitLine)splitLine.style.left=split+'%';splitHandle?.setAttribute('aria-valuenow',String(Math.round(split)));if(instant){after?.style.setProperty('transition','none');splitLine?.style.setProperty('transition','none');requestAnimationFrame(()=>{after?.style.removeProperty('transition');splitLine?.style.removeProperty('transition');});}$$('[data-state]').forEach(b=>b.classList.toggle('active',(b.dataset.state==='before'&&split>92)||(b.dataset.state==='after'&&split<8)||(b.dataset.state==='compare'&&split>=8&&split<=92)));}
function setFromX(x){const r=demo.getBoundingClientRect();setSplit((x-r.left)/r.width*100,true);}
if(demo){
  setSplit(52,true);
  demo.addEventListener('pointerdown',e=>{userTouched=true;dragging=true;horizontal=false;startX=e.clientX;startY=e.clientY;demo.setPointerCapture?.(e.pointerId);});
  demo.addEventListener('pointermove',e=>{if(!dragging)return;const dx=e.clientX-startX,dy=e.clientY-startY;if(!horizontal&&Math.abs(dx)>8&&Math.abs(dx)>Math.abs(dy))horizontal=true;if(horizontal){e.preventDefault();setFromX(e.clientX);}});
  const stop=e=>{dragging=false;horizontal=false;try{demo.releasePointerCapture?.(e.pointerId);}catch(_){}};
  demo.addEventListener('pointerup',stop);demo.addEventListener('pointercancel',stop);
  splitHandle?.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'){setSplit(split-5);e.preventDefault();}if(e.key==='ArrowRight'){setSplit(split+5);e.preventDefault();}if(e.key==='Home'){setSplit(0);e.preventDefault();}if(e.key==='End'){setSplit(100);e.preventDefault();}userTouched=true;});
  $$('[data-state]').forEach(b=>b.addEventListener('click',()=>{userTouched=true;setSplit(b.dataset.state==='before'?100:b.dataset.state==='after'?0:52);}));
  if('IntersectionObserver'in window){const io=new IntersectionObserver(entries=>{if(!entries[0].isIntersecting)return;io.disconnect();if(matchMedia('(prefers-reduced-motion:reduce)').matches)return;setTimeout(()=>{if(!userTouched)setSplit(86);},300);setTimeout(()=>{if(!userTouched)setSplit(14);},1500);setTimeout(()=>{if(!userTouched)setSplit(52);},3100);},{threshold:.45});io.observe(demo);}
}

// Section 02: desktop uses the original sticky card; mobile receives a compact fixed strip.
const loss=$('#economics'),steps=$$('#lossSteps article'),lossMoney=$('#lossMoney'),lossDays=$('#lossDays'),lossLabel=$('#lossLabel'),lossBar=$('#lossBar');
const strip=document.createElement('aside');strip.className='loss-strip';strip.innerHTML='<div><small>Полная замена</small><strong id="stripMoney">0 ₽</strong></div><div class="loss-strip__current"><span id="stripLabel">Начало расчёта</span><b id="stripDelta">+0 ₽</b></div><div class="loss-strip__compare"><small>Восстановление</small><b>96 000 ₽</b></div><i id="stripBar"></i>';document.body.appendChild(strip);
const stripMoney=$('#stripMoney'),stripLabel=$('#stripLabel'),stripDelta=$('#stripDelta'),stripBar=$('#stripBar');
function daysText(n){return n+' '+(n===1?'день':n>1&&n<5?'дня':'дней');}
function updateLoss(){if(!loss||!steps.length)return;const rect=loss.getBoundingClientRect(),active=rect.top<innerHeight-72&&rect.bottom>80;strip.classList.toggle('active',active&&innerWidth<=760);let idx=-1;const trigger=Math.min(innerHeight*.62,540);steps.forEach((step,i)=>{if(step.getBoundingClientRect().top<trigger)idx=i;});idx=Math.max(-1,Math.min(steps.length-1,idx));let total=0,days=0;for(let i=0;i<=idx;i++){total+=Number(steps[i].dataset.money||0);days+=Number(steps[i].dataset.days||0);}steps.forEach((step,i)=>step.classList.toggle('active',i<=idx));const current=idx>=0?steps[idx]:null,label=current?.dataset.label||'Начало расчёта',delta=current?Number(current.dataset.money||0):0,percent=idx<0?0:(idx+1)/steps.length*100;if(Number(lossMoney?.dataset.value||0)!==total){lossMoney.dataset.value=String(total);animateMoney(lossMoney,total);animateMoney(stripMoney,total);}if(lossDays)lossDays.textContent=daysText(days);if(lossLabel)lossLabel.textContent=label;if(lossBar)lossBar.style.width=percent+'%';stripLabel.textContent=label;stripDelta.textContent='+'+fullRub(delta);stripBar.style.width=percent+'%';}

const modes={replace:{label:'Полная замена',title:'Новое стекло: замер, производство, доставка, демонтаж и повторный монтаж',money:312000,days:'18–21 день',result:'До 21 дня и несколько подрядчиков',text:'Срок зависит от производства, доставки и монтажа',steps:[['Повторный замер','1–2 дня',1],['Производство стекла','10–18 дней',1],['Доставка и подъём','1–2 дня',1],['Демонтаж и монтаж','1–2 дня',1],['Отделка и сдача','1 день',1]]},restore:{label:'Восстановление на объекте',title:'Обрабатываем повреждённый участок без демонтажа стекла',money:96000,days:'около 2 дней',result:'Экономия в примере — 216 000 ₽',text:'Без ожидания производства, доставки и повторного монтажа',steps:[['Фото и диагностика','в день обращения',1],['Тестовый участок','при необходимости',1],['Работы на объекте','1–3 дня',1],['Приёмка и документы','в день окончания',1],['Производство и доставка','не требуются',0]]}};
const decisionLabel=$('#decisionLabel'),decisionTitle=$('#decisionTitle'),decisionMoney=$('#decisionMoney'),decisionDays=$('#decisionDays'),decisionResult=$('#decisionResult'),decisionResultText=$('#decisionResultText'),timeline=$$('#timeline>div');
function setMode(name){const m=modes[name];if(!m)return;$$('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===name));decisionLabel.textContent=m.label;decisionTitle.textContent=m.title;animateMoney(decisionMoney,m.money,500);decisionDays.textContent=m.days;decisionResult.textContent=m.result;decisionResultText.textContent=m.text;timeline.forEach((el,i)=>{const s=m.steps[i];$('span',el).textContent=s[0];$('small',el).textContent=s[1];el.classList.toggle('off',!s[2]);});}
$$('[data-mode]').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.mode)));setMode('restore');

const form=$('#calculatorForm'),replacementRange=$('#replacementRange'),restorationRange=$('#restorationRange'),savingMoney=$('#savingMoney'),savingPercent=$('#savingPercent'),calcVerdict=$('#calcVerdict'),replacementTime=$('#replacementTime'),restorationTime=$('#restorationTime'),savingBlock=$('#savingBlock');
function calculate(){if(!form)return null;const d=new FormData(form),object=Number(d.get('object')),area=Math.max(.2,Number(d.get('area'))||.2),pieces=Math.max(1,Number(d.get('pieces'))||1),damage=Number(d.get('damage')),access=Number(d.get('access')||1),urgency=Number(d.get('urgency')||1),known=Number(d.get('known'))||0;const restoration=Math.max(4000,(6200*area+1800*pieces)*object*damage*access*urgency),restLow=Math.round(restoration*.9),restHigh=Math.round(restoration*1.14);let replLow,replHigh;if(known>0){replLow=Math.round(known*.97);replHigh=Math.round(known*1.03);}else{let replacement=(14800*area+23500*pieces+42000)*object*Math.max(1,.94*access);if(urgency>1.25)replacement*=1.08;replLow=Math.round(replacement*.9);replHigh=Math.round(replacement*1.14);}const saveLow=replLow-restHigh,saveHigh=replHigh-restLow;replacementRange.textContent=compactRange(replLow,replHigh);restorationRange.textContent=compactRange(restLow,restHigh);restorationTime.textContent=urgency>=1.35?'день в день':area<=6?'от нескольких часов':area<=20?'1–3 дня':'от 3 дней';replacementTime.textContent=area>20?'18–28 дней':'14–21 день';savingBlock.classList.remove('warning','negative');let verdict,moneyText,percentText;if(saveHigh<=0){verdict='В этом случае замена может оказаться выгоднее';moneyText=`Восстановление дороже на ${compactRange(Math.abs(saveHigh),Math.abs(saveLow))}`;percentText='Нужны фотографии, чтобы не ошибиться с решением';savingBlock.classList.add('negative');}else if(saveLow<=0){verdict='Без фотографий решение принимать рано';moneyText=`Разница — от 0 до ${compact(saveHigh)}`;percentText='Диапазоны пересекаются: нужен осмотр или тест';savingBlock.classList.add('warning');}else{const low=Math.min(67,Math.max(0,Math.round(saveLow/replHigh*100))),high=Math.min(67,Math.max(low,Math.round(saveHigh/replLow*100)));verdict=saveHigh>90000?'По расчёту восстановление заметно выгоднее':'Стекло стоит проверить по фото';moneyText=compactRange(saveLow,saveHigh);percentText=low===67?'экономия до 67% к стоимости замены':`экономия примерно ${low}–${high}%`;}calcVerdict.textContent=verdict;savingMoney.textContent=moneyText;savingPercent.textContent=percentText;return{d,verdict};}
form?.addEventListener('input',calculate);calculate();
$('#sendCalculation')?.addEventListener('click',()=>{const r=calculate(),d=r.d,text=`Здравствуйте. Хочу понять, можно ли восстановить стекло без замены.\n\nПлощадь: ${d.get('area')} м²\nКоличество стёкол: ${d.get('pieces')}\nОриентир по замене: ${replacementRange.textContent}\nОриентир по восстановлению: ${restorationRange.textContent}\nВывод: ${r.verdict}\n\nСейчас пришлю фотографии.`;showToast('Открываем Telegram @zhukov_boss');location.assign(TELEGRAM+'?text='+encodeURIComponent(text));});

const completion=$('#completionFlow');if(completion&&'IntersectionObserver'in window){const io=new IntersectionObserver(e=>{if(e[0].isIntersecting){completion.classList.add('visible');io.disconnect();}},{threshold:.3});io.observe(completion);}
const finalCta=$('#finalCta');if(finalCta&&mobileCta&&'IntersectionObserver'in window){new IntersectionObserver(e=>mobileCta.classList.toggle('hide',e[0].isIntersecting),{threshold:.12}).observe(finalCta);}
$$('input,select').forEach(el=>{el.addEventListener('focus',()=>mobileCta?.classList.add('keyboard'));el.addEventListener('blur',()=>setTimeout(()=>mobileCta?.classList.remove('keyboard'),180));});
function onScroll(){if(scrollRaf)return;scrollRaf=requestAnimationFrame(()=>{scrollRaf=0;const h=document.documentElement.scrollHeight-innerHeight;if(progress)progress.style.width=(h?scrollY/h*100:0)+'%';mobileCta?.classList.toggle('show',scrollY>520);updateLoss();});}
addEventListener('scroll',onScroll,{passive:true});addEventListener('resize',onScroll,{passive:true});onScroll();updateLoss();
})();
