(()=>{
'use strict';
const $=(s,c=document)=>c.querySelector(s), $$=(s,c=document)=>[...c.querySelectorAll(s)];
const fullRub=n=>new Intl.NumberFormat('ru-RU').format(Math.round(n/1000)*1000)+' ₽';
const compact=n=>{n=Math.max(0,n);if(n>=1e6)return (n/1e6).toLocaleString('ru-RU',{minimumFractionDigits:n<1e7?2:1,maximumFractionDigits:2})+' млн ₽';if(n>=1e5)return Math.round(n/1000).toLocaleString('ru-RU')+' тыс. ₽';return fullRub(n)};
const compactRange=(a,b)=>Math.abs(b-a)<5000?compact((a+b)/2):`${compact(a)} — ${compact(b)}`;
const progress=$('#pageProgress'),mobileCta=$('#mobileCta');let scrollRaf=0;
function animateMoney(el,to,duration=560){if(!el)return;const from=Number(el.dataset.current||String(el.textContent).replace(/\D/g,'')||0),start=performance.now();cancelAnimationFrame(el._raf);function tick(now){const t=Math.min(1,(now-start)/duration),v=Math.round(from+(to-from)*(1-Math.pow(1-t,3)));el.textContent=fullRub(v);if(t<1)el._raf=requestAnimationFrame(tick);else el.dataset.current=String(to)}el._raf=requestAnimationFrame(tick)}
function onScroll(){if(scrollRaf)return;scrollRaf=requestAnimationFrame(()=>{scrollRaf=0;const h=document.documentElement.scrollHeight-innerHeight;if(progress)progress.style.width=(h>0?scrollY/h*100:0)+'%';mobileCta?.classList.toggle('show',scrollY>520);updateLoss();});}addEventListener('scroll',onScroll,{passive:true});addEventListener('resize',onScroll,{passive:true});
const demo=$('#beforeAfter'),after=$('#afterLayer'),splitLine=$('#splitLine'),splitHandle=$('#splitHandle');let split=52,dragging=false,userTouched=false,startX=0,startY=0,horizontal=false;
function setSplit(pos,instant=false){if(!demo)return;split=Math.max(0,Math.min(100,pos));demo.style.setProperty('--split',split+'%');if(after)after.style.clipPath=`inset(0 ${100-split}% 0 0)`;if(splitLine)splitLine.style.left=split+'%';splitHandle?.setAttribute('aria-valuenow',String(Math.round(split)));if(instant){after?.style.setProperty('transition','none');splitLine?.style.setProperty('transition','none');requestAnimationFrame(()=>{after?.style.removeProperty('transition');splitLine?.style.removeProperty('transition')})}$$('[data-state]').forEach(b=>b.classList.toggle('active',(b.dataset.state==='before'&&split<8)||(b.dataset.state==='after'&&split>92)||(b.dataset.state==='compare'&&split>=8&&split<=92)));}
function setSplitFromX(x){const r=demo.getBoundingClientRect();setSplit((x-r.left)/r.width*100,true)}
if(demo){setSplit(52,true);demo.addEventListener('pointerdown',e=>{userTouched=true;dragging=true;horizontal=false;startX=e.clientX;startY=e.clientY;demo.setPointerCapture?.(e.pointerId)});demo.addEventListener('pointermove',e=>{if(!dragging)return;const dx=e.clientX-startX,dy=e.clientY-startY;if(!horizontal&&Math.abs(dx)>8&&Math.abs(dx)>Math.abs(dy))horizontal=true;if(horizontal){e.preventDefault();setSplitFromX(e.clientX)}});const end=e=>{dragging=false;horizontal=false;demo.releasePointerCapture?.(e.pointerId)};demo.addEventListener('pointerup',end);demo.addEventListener('pointercancel',end);splitHandle?.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'){userTouched=true;setSplit(split-5);e.preventDefault()}if(e.key==='ArrowRight'){userTouched=true;setSplit(split+5);e.preventDefault()}if(e.key==='Home'){userTouched=true;setSplit(0);e.preventDefault()}if(e.key==='End'){userTouched=true;setSplit(100);e.preventDefault()}});$$('[data-state]').forEach(b=>b.addEventListener('click',()=>{userTouched=true;setSplit(b.dataset.state==='before'?0:b.dataset.state==='after'?100:52)}));if('IntersectionObserver'in window){const io=new IntersectionObserver(entries=>{if(entries[0].isIntersecting){io.disconnect();if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;setTimeout(()=>{if(!userTouched)setSplit(12)},220);setTimeout(()=>{if(!userTouched)setSplit(88)},1250);setTimeout(()=>{if(!userTouched)setSplit(52)},2850)}},{threshold:.42});io.observe(demo)}}
const loss=$('#economics'),lossSteps=$$('#lossSteps article'),lossMoney=$('#lossMoney'),lossDays=$('#lossDays'),lossLabel=$('#lossLabel'),lossBar=$('#lossBar');
function updateLoss(){if(!loss||!lossSteps.length)return;const rect=loss.getBoundingClientRect(),vh=innerHeight,start=vh*.72,end=Math.max(1,rect.height-vh*.45),raw=(start-rect.top)/end,p=Math.max(0,Math.min(.999,raw)),idx=raw<=0?-1:Math.min(lossSteps.length-1,Math.floor(p*lossSteps.length));lossSteps.forEach((step,i)=>step.classList.toggle('active',i<=idx));let total=0,days=0;for(let i=0;i<=idx;i++){total+=Number(lossSteps[i].dataset.money||0);days+=Number(lossSteps[i].dataset.days||0)}if(Number(lossMoney?.dataset.value||0)!==total){lossMoney.dataset.value=String(total);animateMoney(lossMoney,total,420)}if(lossDays)lossDays.textContent=days+' '+(days===1?'день':days<5?'дня':'дней');if(lossLabel)lossLabel.textContent=idx<0?'Начало расчёта':lossSteps[idx].dataset.label;if(lossBar)lossBar.style.width=(idx<0?0:(idx+1)/lossSteps.length*100)+'%';}
const modes={replace:{label:'Сценарий A · Полная замена',title:'Разбираем готовую конструкцию и собираем процесс заново',money:312000,days:'18–21 день',result:'Риск переноса сроков',text:'Пять этапов и несколько исполнителей',active:['measure','production','delivery','dismantle','finish']},restore:{label:'Сценарий B · Восстановление',title:'Работаем с установленным стеклом прямо на объекте',money:96000,days:'около 2 дней',result:'Потенциальная экономия — 216 000 ₽',text:'Без производства, логистики и демонтажа',active:['measure','finish']}};
const decisionLabel=$('#decisionLabel'),decisionTitle=$('#decisionTitle'),decisionMoney=$('#decisionMoney'),decisionDays=$('#decisionDays'),decisionResult=$('#decisionResult'),decisionResultText=$('#decisionResultText'),timeline=$$('#timeline>div');let modeTouched=false;
function setMode(name,user=false){const m=modes[name];if(!m)return;if(user)modeTouched=true;$$('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===name));decisionLabel.textContent=m.label;decisionTitle.textContent=m.title;animateMoney(decisionMoney,m.money,650);decisionDays.textContent=m.days;decisionResult.textContent=m.result;decisionResultText.textContent=m.text;timeline.forEach(el=>el.classList.toggle('off',!m.active.includes(el.dataset.step)))}$$('[data-mode]').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.mode,true)));setMode('replace');const decisionBoard=$('#decisionBoard');if(decisionBoard&&'IntersectionObserver'in window){const io=new IntersectionObserver(e=>{if(e[0].isIntersecting){io.disconnect();setTimeout(()=>{if(!modeTouched)setMode('restore')},1050)}},{threshold:.4});io.observe(decisionBoard)}
const form=$('#calculatorForm'),replacementRange=$('#replacementRange'),restorationRange=$('#restorationRange'),savingMoney=$('#savingMoney'),savingPercent=$('#savingPercent'),calcVerdict=$('#calcVerdict'),replacementTime=$('#replacementTime'),restorationTime=$('#restorationTime'),savingBlock=$('#savingBlock');
function calculate(){if(!form)return null;const d=new FormData(form),object=Number(d.get('object')),area=Math.max(.2,Number(d.get('area'))||.2),pieces=Math.max(1,Number(d.get('pieces'))||1),damage=Number(d.get('damage')),access=Number(d.get('access')||1),urgency=Number(d.get('urgency')||1),known=Number(d.get('known'))||0;const restoration=Math.max(4000,(6200*area+1800*pieces)*object*damage*access*urgency),restLow=Math.round(restoration*.9),restHigh=Math.round(restoration*1.14);let replLow,replHigh;if(known>0){replLow=Math.round(known*.97);replHigh=Math.round(known*1.03)}else{let replacement=(14800*area+23500*pieces+42000)*object*Math.max(1,.94*access);if(urgency>1.25)replacement*=1.08;replLow=Math.round(replacement*.9);replHigh=Math.round(replacement*1.14)}const saveLow=replLow-restHigh,saveHigh=replHigh-restLow;replacementRange.textContent=compactRange(replLow,replHigh);restorationRange.textContent=compactRange(restLow,restHigh);const restDays=urgency>=1.35?'день в день':area<=6?'от нескольких часов':area<=20?'1–3 дня':'от 3 дней';restorationTime.textContent=restDays;replacementTime.textContent=area>20?'18–28 дней':'14–21 день';savingBlock.classList.remove('warning','negative');let verdict,percentText,moneyText;if(saveHigh<=0){const extraLow=Math.abs(saveHigh),extraHigh=Math.abs(saveLow);verdict='По введённым данным замена может быть рациональнее';moneyText=`Восстановление дороже на ${compactRange(extraLow,extraHigh)}`;percentText='Нужна диагностика перед решением';savingBlock.classList.add('negative')}else if(saveLow<=0){verdict='Результат зависит от состояния стекла';moneyText=`От 0 до ${compact(saveHigh)}`;percentText='Диапазоны пересекаются — нужен осмотр';savingBlock.classList.add('warning')}else{const pctLow=Math.min(67,Math.max(0,Math.round(saveLow/replHigh*100))),pctHigh=Math.min(67,Math.max(pctLow,Math.round(saveHigh/replLow*100)));verdict=saveHigh>90000?'Высокий потенциал экономии':'Восстановление имеет смысл рассмотреть';moneyText=compactRange(saveLow,saveHigh);percentText=pctLow===67?'до 67% относительно замены':`≈ ${pctLow}–${pctHigh}% относительно замены`}calcVerdict.textContent=verdict;savingMoney.textContent=moneyText;savingPercent.textContent=percentText;return{d,replLow,replHigh,restLow,restHigh,saveLow,saveHigh,restDays,verdict};}
form?.addEventListener('input',calculate);calculate();$('#sendCalculation')?.addEventListener('click',()=>{const r=calculate(),d=r.d,object=form.object.options[form.object.selectedIndex].text,damage=form.damage.options[form.damage.selectedIndex].text,access=form.access.options[form.access.selectedIndex].text,urgency=form.urgency.options[form.urgency.selectedIndex].text,text=`Здравствуйте. Хочу получить заключение по восстановлению стекла.\n\nОбъект: ${object}\nПлощадь: ${d.get('area')} м²\nЭлементов: ${d.get('pieces')}\nПовреждение: ${damage}\nДоступ: ${access}\nСрочность: ${urgency}\n\nЗамена: ${replacementRange.textContent}\nВосстановление: ${restorationRange.textContent}\nВывод: ${r.verdict}\nПотенциальная разница: ${savingMoney.textContent}\n\nГотов отправить фотографии.`;window.open('https://t.me/zhukov_boss?text='+encodeURIComponent(text),'_blank','noopener')});
const completion=$('#completionFlow');if(completion&&'IntersectionObserver'in window){const io=new IntersectionObserver(es=>{if(es[0].isIntersecting){completion.classList.add('visible');io.disconnect()}},{threshold:.3});io.observe(completion)}
$$('[data-track]').forEach(el=>el.addEventListener('click',()=>{window.dataLayer=window.dataLayer||[];window.dataLayer.push({event:el.dataset.track})}));
onScroll();updateLoss();
})();
